[theme]
base="dark"
primaryColor="#4169E1"  # Royal Blue
backgroundColor="#191970"  # Midnight Blue
secondaryBackgroundColor="#1a1a4d"  # Darker Midnight Blue for secondary elements
textColor="#E6E6FA"  # Lavender for better readability
font="sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true 